version: '3.8'

services:
  db:
    image: postgres:17
    container_name: engineering-db
    restart: unless-stopped 
    environment:
      POSTGRES_DB: engineeringDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # любые .sql из initsql/ будут выполнены при инициализации
      - ./initsql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  server:
    image: engineering-server:latest
    container_name: engineering-server
    restart: unless-stopped 
    build:
      context: ./server      # папка с вашим Spring Boot JAR и Dockerfile
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/engineeringDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # остальные переменные окружения
      JWT_SECRET: ${JWT_SECRET}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_SECURITY_PASSWORD: ${SPRING_SECURITY_PASSWORD}
      YANDEX_CLOUD_BUCKET: ${YANDEX_CLOUD_BUCKET}
      YANDEX_CLOUD_KEY_ID: ${YANDEX_CLOUD_KEY_ID}
      YANDEX_CLOUD_SECRET_KEY: ${YANDEX_CLOUD_SECRET_KEY}
    ports:
      - "8081:8081"

  recommend:
    image: engineering-recommend:latest
    container_name: engineering-recommend
    restart: unless-stopped 
    build:
      context: ./recommend     # папка с вашим FastAPI-кодом и Dockerfile
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8082"

volumes:
  db-data: