spring:
  application:
    name: diploma
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
    liquibase-schema: public
    default-schema: engineers
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/engineeringDB
  security:
    user:
      name: user
      password: ${SPRING_SECURITY_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/engineeringDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtps




server:
  port: 8081

logging:
  level:
    org.springframework.jdbc: DEBUG
    liquibase: DEBUG


jwtExpirationMs: 1800000
jwtRefreshExpirationMs: 604800000
jwtSecret: ${JWT_SECRET}

yandex-cloud-key-id: ${YANDEX_CLOUD_KEY_ID}
yandex-cloud-secret-key: ${YANDEX_CLOUD_SECRET_KEY}
yandex-cloud-region: ru-central1
yandex-cloud-s3-endpoint: https://storage.yandexcloud.net
yandex-cloud-bucket: ${YANDEX_CLOUD_BUCKET}

recommendation-url: http://recommend:8082
